<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="FASTERONE" name="Command line test" tests="7" failures="2" timestamp="10 May 2014 09:35:58 GMT" time="19.585" errors="0">
  <testcase name="hello" time="0.223" classname="com.joseph.california.test.respository.CustomerRepositoryTest"/>
  <testcase name="createPerson" time="0.078" classname="com.joseph.california.test.respository.PersonRepositoryTest"/>
  <testcase name="total" time="0.66" classname="com.joseph.california.test.services.TotalNumberTest">
    <failure type="java.lang.AssertionError" message=" Expert no People expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError:  Expert no People expected [1] but found [0]
	at com.joseph.california.test.services.TotalNumberTest.total(TotalNumberTest.java:46)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- total -->
  <testcase name="getAgeofPeple" time="0.063" classname="com.joseph.california.test.services.PeopleAgeServiceTest"/>
  <testcase name="readPerson" time="0.033" classname="com.joseph.california.test.respository.PersonRepositoryTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.joseph.california.test.respository.PersonRepositoryTest.readPerson(PersonRepositoryTest.java:56)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- readPerson -->
  <testcase name="updatePerson" time="0.001" classname="com.joseph.california.test.respository.PersonRepositoryTest">
    <skipped/>
  </testcase> <!-- updatePerson -->
  <testcase name="deletePerson" time="0.001" classname="com.joseph.california.test.respository.PersonRepositoryTest">
    <skipped/>
  </testcase> <!-- deletePerson -->
</testsuite> <!-- Command line test -->
